spring : 
    application :
       name : ss-mongo
server : 
    port : 8081
---
spring :
    profiles : dev
server : 
    port : 8080
---
spring : 
    profiles : pub
server : 
    port : 8082
---
spring :
    profiles :
       active : dev