spring : 
    profiles : default
    application :
       name : spring-boot-server
    datasource : 
       url : jdbc:mysql://115.126.86.143/songshare?useUnicode=true&characterEncoding=utf8
       username : root
       password : root
    driver-class-name : com.mysql.jdbc.Driver
    jpa :
       properties :
         hibernate :
            hbm2ddl :
               auto : validate
            dialect : org.hibernate.dialect.MySQLDialect
server :
    port : 8761
---
spring :
    profiles : dev
server : 
    port : 8080
---
spring : 
    profiles : pub
server : 
    port : 8082
---
spring :
    profiles :
       active : default