spring : 
    profiles : default
    application :
       name : spring-boot-server
server :
    port : 8761
eureka : 
    client : 
       registerWithEureka : false
       fetchRegistry : false
       serviceUrl : 
          defaultZone : http://localhost:8761/eureka/
    instance :
       preferIpAddress : true
---
spring :
    profiles : dev
server : 
    port : 8080
---
spring : 
    profiles : pub
server : 
    port : 8082
---
spring :
    profiles :
       active : default