spring : 
    application :
       name : ss-mongo
server : 
    port : 8081
---
spring :
    profiles : dev
    data : 
       mongodb :
         host : 115.126.86.143
         port : 27017
         database : test
server : 
    port : 8080
---
spring : 
    profiles : pub
server : 
    port : 8082
---
spring :
    profiles :
       active : dev